# -*- coding: utf-8 -*-
"""Copia de ACT6_IAYRN_1950271

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6H9Wr-cyv1S98fm0Ym2qHzoLPmVvEsv

# **Actividad 6: Solución de problemas.**
# Marco Antonio Mejía García
# 1950271
# N3 LMV
"""

# Librerías
import matplotlib.pyplot as plt # generar gráficos
import numpy as np # generar arreglos
import pandas as pd # cargar conjuntos de datos externos
from sklearn.linear_model import LinearRegression # contiene diferentes modelos de ML
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Cargar el conjunto de datos
california = fetch_california_housing()
df = pd.DataFrame(data=california.data, columns=california.feature_names)
df['Precio'] = california.target

X = df[['MedInc']] # MedInc (Ingresos medios en la zona)
y = df['Precio']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear el modelo de regresión lineal
model = LinearRegression()

# Entrenar el modelo
model.fit(X_train, y_train)

test_data = np.array([[10000]])

# Realizar predicciones
y_pred = model.predict(X_test)

X_new= [[1.9]] # ING PROM
print(model.predict(X_new))

X_new2 = [[9.8]] # ING PROM
print(model.predict(X_new2))

# Calcular el error cuadrático medio (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Error Cuadrático Medio: {mse}")

# Graficar los datos de prueba y la línea de regresión
plt.figure(figsize=(10, 6))
# Datos de prueba
plt.scatter(X_test, y_test, color='blue', label='Datos reales')
plt.xlabel('Ingreso Promedio')
plt.ylabel('Precio de la Casa')
plt.title('Modelo de Regresión Lineal para la Predicción del Precio de Casas')

# Línea de regresión
plt.scatter(X_test, y_test, color='blue', label='Datos reales')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Modelo de Regresión Lineal')
plt.xlabel('Ingreso Promedio')
plt.ylabel('Precio de la Casa')
plt.title('Modelo de Regresión Lineal para la Predicción del Precio de Casas')
plt.legend()
plt.show()